Repository boostcampwm-2024/refactor-web41-Denannu, pull requests merged in 2025-02, with the labels that each got.

#37 [Feat] 홍보용 피드 요약 기능 추가
  server/src/ai/ai.config.ts
  server/src/ai/ai.module.ts
  server/src/ai/ai.service.ts
  server/src/rss/feed-crawler.service.ts
  server/src/rss/rss.module.ts
Labels: BE, Feat

#39 [Feat] AI 기능 추가 공통 부분 작성
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/feed/feed.entity.ts
  server/src/rss/feed-crawler.service.ts
  server/src/tag/tag.entity.ts
  server/src/tag/tag.module.ts
  server/src/tag/tag.service.ts
  server/test/feed/dto/query-feed.dto.spec.ts
  server/test/feed/dto/query-search.dto.spec.ts
  server/test/rss/feed-crawler.service.spec.ts
Labels: BE, Feat

#35 [Feat] Google Analytics 도입 및 이벤트 관측 코드 추가
  client/index.html
  client/src/hooks/common/usePostCardActions.ts
  client/src/hooks/common/useRssRegistrationForm.ts
  client/src/hooks/queries/useSearch.ts
  client/src/types/gtag.d.ts
  client/src/utils/analytics.ts
  client/tsconfig.json
Labels: Feat, Common

#42 [Feat] 포스트 카드에 태그 목록 추가 기능 구현
  client/src/components/common/Card/PostCardContent.tsx
  client/src/components/common/Card/PostCardTags.tsx
Labels: FE, Feat

#49 [Feat] 태그 검색 기능 추가
  server/src/feed/dto/search-feed.dto.ts
  server/src/feed/feed.repository.ts
  server/src/feed/feed.service.ts
  server/src/tag/tag.entity.ts
Labels: BE, Feat

#50 [Feat] summary 로직 수정 및 feed summary 조회 api 구현
  server/src/ai/ai.config.ts
  server/src/ai/ai.service.ts
  server/src/feed/api-docs/getFeedSummary.api-docs.ts
  server/src/feed/feed.controller.ts
  server/src/feed/feed.service.ts
  server/src/rss/feed-crawler.service.ts
Labels: BE, Feat

#52 [Feat] AI Tag 기능 구현
  server/src/ai/ai.config.ts
  server/src/ai/ai.service.ts
  server/src/feed/dto/feed-response.dto.ts
  server/src/feed/feed.entity.ts
  server/src/feed/feed.repository.ts
  server/src/rss/feed-crawler.service.ts
  server/src/rss/rss.module.ts
  server/src/tag/tag.module.ts
  server/src/tag/tag.repository.ts
  server/src/tag/tag.service.ts
Labels: BE, Feat

#51 [Refactor] RSS 등록 메일 내용 수정
  client/index.html
  server/src/common/email/email.service.ts
  server/src/common/email/mail_content.ts
  server/src/common/swagger/swagger.ts
  server/src/feed/api-docs/searchFeedList.api-docs.ts
Labels: Refactor, Common

#55 [Fix] 1.2.0 릴리즈 오류 수정
  server/src/app.module.ts
  server/src/feed/feed.entity.ts
  server/src/feed/feed.service.ts
  server/src/rss/feed-crawler.service.ts
  server/src/rss/rss.module.ts
  server/test/fixture/feed.fixture.ts
  server/test/jest.setup.ts
  server/test/rss/feed-crawler.service.spec.ts
Labels: Fix

#56 [Fix] 테스트 타임아웃 10초로 변경
  server/test/rss/accept.e2e-spec.ts
Labels: Fix

#58 [FIX] Docker 컨테이너 네이밍 충돌로 인한 실행 실패 fix
  .github/workflows/deploy_server.yml
  dockerfile.server
Labels: Deploy, Fix

#59 [Deploy] Releases 1.2.0
  .github/workflows/deploy_server.yml
  dockerfile.server
Labels: Deploy
