Repository boostcampwm-2024/refactor-web41-Denannu, pull requests merged in 2025-01, with the labels that each got.

#4 [Refactor] TanStack Query 쿼리 키 계층화 및 관련 코드 수정
  client/eslint.config.js
  client/src/components/admin/layout/AdminTabs.tsx
  client/src/components/chart/Chart.tsx
  client/src/hooks/queries/useChart.ts
  client/src/hooks/queries/useFetchRss.ts
  client/src/hooks/queries/useSearch.ts
  commitlint.config.js
  feed-crawler/src/common/constant.ts
  feed-crawler/src/main.ts
Labels: FE, Refactor

#2 [Refactor] 프로젝트 초기 배포
  .github/workflows/deploy_client.yml
  .github/workflows/deploy_server.yml
  docker-compose.yaml
  dockerfile.nginx
  dockerfile.server
  ecosystem.config.js
  feed-crawler/src/common/mysql-access.ts
  nginx.conf
  package-lock.json
  server/src/main.ts
Labels: BE, Refactor, Deploy

#7 [Refactor] staleTime 매직 넘버 constant화
  client/src/constants/time.ts
  client/src/hooks/queries/useChart.ts
  client/src/hooks/queries/useFetchRss.ts
  client/src/hooks/queries/useSearch.ts
Labels: FE, Refactor

#9 [Refactor] 검색 쿼리 최적화
  server/src/feed/feed.repository.ts
Labels: BE, Refactor

#10 [Feat] RSS 등록 폼에 상태 저장 기능 추가
  client/src/components/RssRegistration/RssRegistrationModal.tsx
  client/src/store/useRegisterModalStore.ts
Labels: FE, Refactor

#13 [Fix] Zustand persist 의 partialize 옵션 사용 시 발생한 TypeScript 타입 오류 해결
  client/src/components/RssRegistration/RssRegistrationModal.tsx
  client/src/hooks/common/useRssRegistrationForm.ts
  client/src/store/useRegisterModalStore.ts
Labels: FE, Fix

#16 [Feat] 검색 결과 페이지네이션에 Cursor 방식 적용
  client/src/__tests__/components/common/search/SearchResults/SearchResultList.test.tsx
  client/src/api/services/search.ts
  client/src/components/search/SearchResults/SearchResultList.tsx
  client/src/components/search/searchPages/SearchPages.tsx
  client/src/hooks/queries/useSearch.ts
  client/src/store/useSearchStore.ts
  client/src/types/search.ts
Labels: FE, Feat

#17 [Refactor] 서버 배포 CI/CD
  .dockerignore
  .github/workflows/deploy_client.yml
  .github/workflows/deploy_server.yml
  client/src/api/instance.ts
  client/src/hooks/queries/useTrendingPosts.ts
  client/src/store/useChatStore.ts
  docker-compose.yaml
  feed-crawler/src/main.ts
Labels: BE, Refactor

#24 [Refactor] cursor 적용
  server/src/feed/dto/search-feed.dto.ts
  server/src/feed/feed.repository.ts
  server/src/feed/feed.service.ts
Labels: BE, Refactor

#25 [Refactor] deploy 파일의 잘못된 폴더명 변경
  .github/workflows/deploy_client.yml
  .github/workflows/deploy_server.yml
Labels: BE, Refactor

#28 [Fix] 커서 데이터 누락 문제 해결
  client/src/components/search/searchPages/SearchPages.tsx
  client/src/hooks/queries/useSearch.ts
  client/src/store/useSearchStore.ts
  client/src/types/search.ts
Labels: FE, Fix

#30 [Fix] preIndex, nextIndex의 디폴트 값을 undefined로 통일하여 빌드 에러 해결
  client/src/components/search/searchPages/SearchPages.tsx
  client/src/store/useSearchStore.ts
Labels: FE, Fix

#22 [Refactor] 피드 조회 API 속도 개선
  server/src/feed/dto/feed-response.dto.ts
  server/src/feed/feed.entity.ts
  server/src/feed/feed.repository.ts
  server/src/feed/feed.service.ts
Labels: BE, Refactor

#32 [Refactor] 검색 시 batch 방식 적용 및 최적화
  server/src/feed/feed.repository.ts
  server/src/feed/feed.service.ts
Labels: BE, Refactor
